### ISSUE TITLE
python package elasticsearch-6.0.0 gives unexpected keyword argument 'analyzer'

### ISSUE THREAD

**Issue by schelv** [iai-group/nordlys#14]
Hello,

I followed all the installation instruction succesfully and decided to see if the program can succesfully replicate the [entity retrieval results](https://nordlys.readthedocs.io/en/latest/er.html).

This gave the following error.

````
root@IR:~/nordlys# python -m nordlys.core.retrieval.retrieval data/dbpedia-entity-v2-replication-test/config/retrieval_bm25.config.json
2017-12-13 12:16:26,963 - nordlys - INFO - scoring [INEX_LD-2009022] Szechwan dish food cuisine
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/nordlys/nordlys/core/retrieval/retrieval.py", line 263, in <module>
    main(arg_parser())
  File "/root/nordlys/nordlys/core/retrieval/retrieval.py", line 256, in main
    r.batch_retrieval()
  File "/root/nordlys/nordlys/core/retrieval/retrieval.py", line 209, in batch_retrieval
    results = self.retrieve(queries[query_id])
  File "/root/nordlys/nordlys/core/retrieval/retrieval.py", line 186, in retrieve
    query = self.__elastic.analyze_query(query)
  File "/root/nordlys/nordlys/core/retrieval/elastic.py", line 116, in analyze_query
    tokens = self.__es.indices.analyze(index=self.__index_name, body=query, analyzer=analyzer)["tokens"]
  File "/root/anaconda3/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: analyze() got an unexpected keyword argument 'analyzer'
````

Uninstalling version 6.0.0 of the package and installing 2.3.0 solved the problem.

**Comment by hasibi** [comment]
The code is compatible with elasticsearch>=5.0 and <6.0 (stated in requirements. txt). Otherwise, you may run into issues.

**Comment by imsure318** [comment]
The only thing you need to do in order to use Elasticsearch 6.0 is to change the analyzer to "string" in elastic.py
