### ISSUE TITLE
el.py FileNotFoundError in load_kb_snapshot

### ISSUE THREAD

**Issue by laura-dietz** [iai-group/nordlys#17]
I setup nordlys on my system. Running the entity linking python script, I get stuck on a file not found error with file  'data/el/snapshot_2015_10.txt'  (see below)

The directory el only lists these files

data/el
data/el/yerd
data/el/yerd/qrels_YERD_er.txt
data/el/yerd/qrels_YERD_elq.txt
data/el/yerd/queries_YERD.json
data/el/yerd/YERD_2015_10.tsv
data/el/erd
data/el/erd/qrels_ERD_elq.txt
data/el/erd/queries_ERD.json
data/el/erd/qrels_ERD_er.txt
data/el/model.txt
data/el/config_ltr.json

Any suggestions?

```
$ python -m nordlys.services.el 
2019-06-25 17:27:03,639 - nordlys - INFO - Loading KB snapshot of proper named entities ...
Traceback (most recent call last):
  File "/home/ben/nordlys/anaconda-bin/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ben/nordlys/anaconda-bin/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ben/nordlys/nordlys/nordlys/services/el.py", line 198, in <module>
    main(arg_parser())
  File "/home/ben/nordlys/nordlys/nordlys/services/el.py", line 187, in main
    el = EL(conf, Entity(), ElasticCache(DBPEDIA_INDEX), FeatureCache())
  File "/home/ben/nordlys/nordlys/nordlys/services/el.py", line 90, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/home/ben/nordlys/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'
```

**Comment by hasibi** [comment]
The missing file can be downloaded using the following command:

``https://gustav1.ux.uis.no/downloads/nordlys-v02/snapshot_2015_10.txt -P data/el``

The installation document is updated and now contains this command.
